print(" Programer_3_date_4: created pseudocode for feature 2")
print(" Programer_3_date_15 : completed implementing first half of feature 2")
print(" Programer_3_date_20 : completed implementing second half of feature 2")
print(" Programer_3_date_80 : started a new feature requested by client")
print(" Programer_3_data_84 : completed the new feature")